#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config/cron

# copy config
[[ ! -e /config/config.conf ]] && cp \
	/defaults/config.conf /config/config.conf
[[ ! -e /app/plexemail/web/index.html ]] && \
	cp /defaults/index.html /app/plexemail/web/index.html
[[ ! -e /config/cron/plexemail ]] && cp \
	/defaults/plexemail /config/cron/plexemail

# set crontab
crontab /config/cron/plexemail

# permissions
chown -R abc:abc \
	/config
